# Generated by Django 3.2.7 on 2021-10-06 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('u_app', '0002_apbook_ustest'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('mnumber', models.CharField(max_length=30)),
                ('yemail', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('pic', models.FileField(blank=True, null=True, upload_to='profile/')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttitle', models.CharField(max_length=20)),
                ('tdes', models.CharField(max_length=100)),
                ('tinter', models.CharField(max_length=100)),
                ('tprice', models.CharField(max_length=20)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Newuap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bresult', models.CharField(max_length=20)),
                ('uresult', models.CharField(max_length=30)),
                ('apubook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_app.apbook')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_app.user')),
            ],
        ),
    ]
