# Generated by Django 3.2.7 on 2021-10-06 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuap',
            name='apubook',
        ),
    ]
