# Generated by Django 3.2.7 on 2021-10-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apbook',
            name='ustest',
            field=models.CharField(default='', max_length=30),
        ),
    ]
